Fix erroneous boolean in compose.yml
The word `On` is a boolean in YAML, so we need to use `"On"` instead
because Docker Compose's environment feature expects a string value.

```
$ make up
Starting up containers for my_wordpress_project...
docker-compose pull
ERROR: The Compose file './compose.yml' is invalid because:
services.php.environment.PHP_MAIL_MIXED_LF_AND_CRLF contains true, which is an invalid type, it should be a string, number, or a null
make: *** [docker.mk:16: up] Error 1
```